import React from 'react';
import { ArrowLeft, Shield, Lock, Eye, UserCheck, FileText, Book, AlertCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import MobileFooterNav from '../components/MobileFooterNav';
import PageHeader from '../components/PageHeader';

const Privacy: React.FC = () => {
  const navigate = useNavigate();

  const privacyHighlights = [
    {
      icon: <Shield className="w-6 h-6 text-[#CCFF00]" />,
      title: 'Data Protection',
      content: 'We employ industry-standard encryption and security measures to protect your personal information and transaction data. Your data is stored securely and is never shared with third parties without your explicit consent.'
    },
    {
      icon: <Lock className="w-6 h-6 text-[#CCFF00]" />,
      title: 'Account Security',
      content: 'Your account is protected by secure authentication methods. We recommend enabling two-factor authentication for additional security. Regular security audits are performed to ensure the safety of your account.'
    },
    {
      icon: <Eye className="w-6 h-6 text-[#CCFF00]" />,
      title: 'Privacy Controls',
      content: 'You have full control over your privacy settings. Choose what information is visible to others and manage your notification preferences. Your betting history and wallet balance are always kept private.'
    },
    {
      icon: <UserCheck className="w-6 h-6 text-[#CCFF00]" />,
      title: 'User Rights',
      content: 'You have the right to access, modify, or delete your personal data at any time. Contact our support team for assistance with data-related requests. We comply with all applicable data protection regulations.'
    }
  ];

  return (
    <div className="min-h-screen bg-[#F6F7FB] pb-[72px]">
      <PageHeader title="Privacy Policy" />

      <div className="p-4 max-w-2xl mx-auto space-y-6">
        {/* Privacy Policy Header */}
        <div className="bg-[#242538] rounded-xl p-6">
          <h2 className="text-white font-bold text-xl mb-2">Privacy Policy</h2>
          <p className="text-white/60 text-sm mb-4">Last updated: April 27, 2025</p>
          <div className="space-y-4 text-white/60">
            <p>
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p>
              Interpretation and Definitions
Interpretation
The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

Definitions
For the purposes of this Privacy Policy:

Account means a unique account created for You to access our Service or parts of our Service.

Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.

Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Oxplay Media LTD, 7a, Lateef Jakande rd, ikeja.

Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.

Country refers to: Nigeria

Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.

Personal Data is any information that relates to an identified or identifiable individual.

Service refers to the Website.

Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.

Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.

Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).

Website refers to Bantah, accessible from https://www.bantah.app/

You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
            </p>
          </div>
        </div>

        {/* Key Privacy Highlights */}
        <div className="bg-[#242538] rounded-xl p-6">
          <h2 className="text-white font-bold text-lg mb-4">Key Privacy Highlights</h2>
          <div className="space-y-4">
            {privacyHighlights.map((section, index) => (
              <div key={index} className="mb-4">
                <div className="flex items-center gap-4 mb-2">
                  <div className="w-10 h-10 rounded-xl bg-[#CCFF00]/20 flex items-center justify-center">
                    {section.icon}
                  </div>
                  <h3 className="text-white font-bold">{section.title}</h3>
                </div>
                <p className="text-white/60 leading-relaxed pl-14">{section.content}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Interpretation and Definitions */}
        <div className="bg-[#242538] rounded-xl p-6">
          <div className="flex items-center gap-4 mb-4">
            <div className="w-12 h-12 rounded-xl bg-[#CCFF00]/20 flex items-center justify-center">
              <Book className="w-6 h-6 text-[#CCFF00]" />
            </div>
            <h2 className="text-white font-bold text-lg">Interpretation and Definitions</h2>
          </div>
          <div className="space-y-4 text-white/60">
            <h3 className="text-white font-semibold text-base">Interpretation</h3>
            <p>
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3 className="text-white font-semibold text-base">Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><span className="font-medium">Account</span> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><span className="font-medium">Affiliate</span> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><span className="font-medium">Company</span> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Oxplay Media LTD, 7a, Lateef Jakande rd, ikeja.</li>
              <li><span className="font-medium">Cookies</span> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><span className="font-medium">Country</span> refers to: Nigeria</li>
              <li><span className="font-medium">Device</span> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><span className="font-medium">Personal Data</span> is any information that relates to an identified or identifiable individual.</li>
              <li><span className="font-medium">Service</span> refers to the Website.</li>
              <li><span className="font-medium">Service Provider</span> means any natural or legal person who processes the data on behalf of the Company.</li>
              <li><span className="font-medium">Third-party Social Media Service</span> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
              <li><span className="font-medium">Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><span className="font-medium">Website</span> refers to Bantah, accessible from https://www.bantah.app/</li>
              <li><span className="font-medium">You</span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
          </div>
        </div>

        {/* Collecting and Using Your Personal Data */}
        <div className="bg-[#242538] rounded-xl p-6">
          <div className="flex items-center gap-4 mb-4">
            <div className="w-12 h-12 rounded-xl bg-[#CCFF00]/20 flex items-center justify-center">
              <FileText className="w-6 h-6 text-[#CCFF00]" />
            </div>
            <h2 className="text-white font-bold text-lg">Collecting and Using Your Personal Data</h2>
          </div>
          <div className="space-y-4 text-white/60">
            <h3 className="text-white font-semibold text-base">Types of Data Collected</h3>

            <h4 className="text-white font-medium">Personal Data</h4>
            <p>
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc pl-6">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="text-white font-medium">Usage Data</h4>
            <p>
              Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p>
              When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
            </p>

            <h4 className="text-white font-medium">Information from Third-Party Social Media Services</h4>
            <p>
              The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:
            </p>
            <ul className="list-disc pl-6">
              <li>Google</li>
              <li>Facebook</li>
              <li>Instagram</li>
              <li>Twitter</li>
              <li>LinkedIn</li>
            </ul>
            <p>
              If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.
            </p>

            <h4 className="text-white font-medium">Tracking Technologies and Cookies</h4>
            <p>
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
            </p>
            <p>
              You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.
            </p>
          </div>
        </div>

        {/* Use of Your Personal Data */}
        <div className="bg-[#242538] rounded-xl p-6">
          <h3 className="text-white font-semibold text-base mb-3">Use of Your Personal Data</h3>
          <div className="space-y-3 text-white/60">
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
              <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
              <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
              <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
              <li>To provide You with news, special offers and general information about other goods, services and events which we offer.</li>
              <li>To manage Your requests: To attend and manage Your requests to Us.</li>
              <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
              <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
            </ul>
          </div>
        </div>

        {/* Security and Retention */}
        <div className="bg-[#242538] rounded-xl p-6">
          <div className="flex items-center gap-4 mb-4">
            <div className="w-12 h-12 rounded-xl bg-[#CCFF00]/20 flex items-center justify-center">
              <Shield className="w-6 h-6 text-[#CCFF00]" />
            </div>
            <h2 className="text-white font-bold text-lg">Security and Data Retention</h2>
          </div>
          <div className="space-y-4 text-white/60">
            <h3 className="text-white font-semibold text-base">Security of Your Personal Data</h3>
            <p>
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>

            <h3 className="text-white font-semibold text-base">Retention of Your Personal Data</h3>
            <p>
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
            </p>
            <p>
              The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
            </p>
          </div>
        </div>

        {/* Your Rights */}
        <div className="bg-[#242538] rounded-xl p-6">
          <div className="flex items-center gap-4 mb-4">
            <div className="w-12 h-12 rounded-xl bg-[#CCFF00]/20 flex items-center justify-center">
              <UserCheck className="w-6 h-6 text-[#CCFF00]" />
            </div>
            <h2 className="text-white font-bold text-lg">Your Rights</h2>
          </div>
          <div className="space-y-4 text-white/60">
            <p>
              You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
            </p>
            <p>
              Our Service may give You the ability to delete certain information about You from within the Service. You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
            </p>
            <p>
              Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
            </p>
          </div>
        </div>

        {/* Contact Us */}
        <div className="bg-[#242538] rounded-xl p-6">
          <div className="flex items-center gap-4 mb-4">
            <div className="w-12 h-12 rounded-xl bg-[#CCFF00]/20 flex items-center justify-center">
              <AlertCircle className="w-6 h-6 text-[#CCFF00]" />
            </div>
            <h2 className="text-white font-bold text-lg">Contact Us</h2>
          </div>
          <div className="space-y-4 text-white/60">
            <p>
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <p>
              By email: <a href="mailto:support@bantah.app" className="text-[#CCFF00]">support@bantah.app</a>
            </p>
          </div>
        </div>
      </div>

      <MobileFooterNav />
    </div>
  );
};

export default Privacy;